# Generated by Django 4.0.1 on 2022-01-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_desenvolvedor_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desenvolvedor',
            name='linkedin',
        ),
    ]
